In [1]:
import numpy as np
import pandas as pd
import seaborn as sns 
import matplotlib.pyplot as plt

In [2]:
#匯入資料
data = pd.read_csv('data/electricity.csv')

In [3]:
# 針對用電量設定類別
def get_consumption_category(wt):
    if wt < 200:
        return 1
    elif 200 < wt < 400:
        return 2
    elif 400 < wt < 600:
        return 3
    elif 600 < wt < 800:
        return 4
    elif 800 < wt < 1000:
        return 5
    elif 1000 < wt < 1200:
        return 6
    else:
        return 7
  
data["electricity_consumption_category"] = data["electricity_consumption"].map(get_consumption_category)
data

ID             datetime  temperature  var1  pressure  windspeed  \
0          0  2013-07-01 00:00:00        -11.4 -17.1    1003.0    571.910   
1          1  2013-07-01 01:00:00        -12.1 -19.3     996.0    575.040   
2          2  2013-07-01 02:00:00        -12.9 -20.0    1000.0    578.435   
3          3  2013-07-01 03:00:00        -11.4 -17.1     995.0    582.580   
4          4  2013-07-01 04:00:00        -11.4 -19.3    1005.0    586.600   
5          5  2013-07-01 05:00:00        -10.7 -19.3    1013.0      2.790   
6          6  2013-07-01 06:00:00        -13.6 -17.1    1006.0      4.380   
7          7  2013-07-01 07:00:00        -11.4 -17.9     997.0      7.635   
8          8  2013-07-01 08:00:00        -10.7 -18.6    1012.0     12.055   
9          9  2013-07-01 09:00:00        -10.0 -16.4    1002.0     17.975   
10        10  2013-07-01 10:00:00         -7.1 -17.1    1008.0     23.035   
11        11  2013-07-01 11:00:00         -7.9 -17.9    1003.0     28.205   
12        12  2013-07-01 12:00:00         -5.7 -15.0     998.0     31.725   
13        13  2013-07-01 13:00:00         -6.4 -14.3    1008.0     35.620   
14        14  2013-07-01 14:00:00         -3.6 -15.0     999.0     40.915   
15        15  2013-07-01 15:00:00         -5.0 -14.3     997.0     44.560   
16        16  2013-07-01 16:00:00         -4.3 -16.4    1009.0     48.440   
17        17  2013-07-01 17:00:00         -7.1 -18.6    1003.0     50.355   
18        18  2013-07-01 18:00:00         -7.1 -16.4    1007.0     53.235   
19        19  2013-07-01 19:00:00         -6.4 -16.4     996.0     56.365   
20        20  2013-07-01 20:00:00         -7.9 -17.1     997.0     59.870   
21        21  2013-07-01 21:00:00         -6.4 -15.7     996.0     63.515   
22        22  2013-07-01 22:00:00         -9.3 -15.7    1015.0     67.410   
23        23  2013-07-01 23:00:00        -10.0 -16.4    1012.0     72.080   
24        24  2013-07-02 00:00:00         -8.6 -14.3    1003.0     76.350   
25        25  2013-07-02 01:00:00         -7.9 -17.1    1011.0      5.770   
26        26  2013-07-02 02:00:00         -8.6 -14.3    1000.0     10.065   
27        27  2013-07-02 03:00:00        -10.7 -15.7     997.0      5.520   
28        28  2013-07-02 04:00:00        -10.7 -14.3    1016.0      4.770   
29        29  2013-07-02 05:00:00         -8.6 -16.4    1015.0      9.665   
...      ...                  ...          ...   ...       ...        ...   
26466  34866  2017-06-22 18:00:00         -3.6 -11.4     988.0      2.265   
26467  34867  2017-06-22 19:00:00         -2.1 -11.4     987.0      3.040   
26468  34868  2017-06-22 20:00:00          0.0 -12.9     982.0      6.685   
26469  34869  2017-06-22 21:00:00         -5.7 -13.6     989.0      8.350   
26470  34870  2017-06-22 22:00:00         -3.6 -12.1     988.0     13.495   
26471  34871  2017-06-22 23:00:00         -5.7 -15.0    1001.0      3.665   
26472  34872  2017-06-23 00:00:00         -2.9 -13.6     992.0      1.890   
26473  34873  2017-06-23 01:00:00         -6.4 -12.9     987.0      3.880   
26474  34874  2017-06-23 02:00:00         -2.9 -15.0     989.0      7.775   
26475  34875  2017-06-23 03:00:00         -8.6 -15.0    1004.0     13.045   
26476  34876  2017-06-23 04:00:00         -7.1 -12.1    1002.0     16.815   
26477  34877  2017-06-23 05:00:00         -6.4 -12.1     996.0     21.360   
26478  34878  2017-06-23 06:00:00         -8.6 -15.0    1003.0     25.505   
26479  34879  2017-06-23 07:00:00         -7.1 -14.3     994.0     28.510   
26480  34880  2017-06-23 08:00:00         -6.4 -12.1    1006.0     30.925   
26481  34881  2017-06-23 09:00:00         -2.9 -12.1     993.0      2.540   
26482  34882  2017-06-23 10:00:00         -2.1 -13.6    1014.0      8.085   
26483  34883  2017-06-23 11:00:00         -2.9 -15.0    1006.0     12.255   
26484  34884  2017-06-23 12:00:00         -1.4 -15.7    1001.0      6.670   
26485  34885  2017-06-23 13:00:00          0.0 -12.1    1002.0     12.695   
26486 

In [4]:
#只列出指定的欄位
df = data[['temperature','pressure', 'windspeed', 'electricity_consumption_category']]
print(type(df))

#檢視前 5 筆資料
df.head()

<class 'pandas.core.frame.DataFrame'>


temperature  pressure  windspeed  electricity_consumption_category
0        -11.4    1003.0    571.910                                 2
1        -12.1     996.0    575.040                                 2
2        -12.9    1000.0    578.435                                 2
3        -11.4     995.0    582.580                                 2
4        -11.4    1005.0    586.600                                 2

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26496 entries, 0 to 26495
Data columns (total 4 columns):
temperature                         26496 non-null float64
pressure                            26496 non-null float64
windspeed                           26496 non-null float64
electricity_consumption_category    26496 non-null int64
dtypes: float64(3), int64(1)
memory usage: 828.1 KB


In [6]:
from sklearn import model_selection
from sklearn.ensemble import AdaBoostClassifier

df = data[['temperature','pressure', 'windspeed', 'electricity_consumption_category']]
array = df.values
#print(array)
X = array[:,0:3]
Y = array[:,3]
seed = 7
num_trees = 30

kfold = model_selection.KFold(n_splits=10, random_state=seed)
model = AdaBoostClassifier(n_estimators=num_trees, random_state=seed)
results = model_selection.cross_val_score(model, X, Y, cv=kfold)
print(results.mean())

0.6797628866713676


In [7]:
X=df.drop('electricity_consumption_category', axis=1)
y=df['electricity_consumption_category']

from sklearn.cross_validation import train_test_split
#分割訓練和測試集
X_train, X_test, y_train, y_test=train_test_split(X, y, test_size=0.3, random_state=101)

from sklearn.ensemble import AdaBoostClassifier
clf = AdaBoostClassifier(n_estimators=100)
clf.fit(X_train, y_train)
y_pred= clf.predict(X_test)
print(y_pred)

D:\Anaconda3\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


[1 2 7 ... 7 2 1]


In [8]:
for estimator in clf.estimators_:
    print(estimator.predict(X_test))
    print(clf.estimator_errors_)

[2 2 2 ... 2 2 2]
[0.23658813 0.7343336  0.7873358  0.79949855 0.79854121 0.81186566
 0.78629734 0.81150634 0.83749889 0.77780485 0.81353455 0.80337271
 0.79062784 0.81898519 0.79777369 0.81836587 0.7874081  0.82903792
 0.82676275 0.81363494 0.76646276 0.79684687 0.83412374 0.80268477
 0.79086489 0.78650595 0.78257925 0.82008096 0.78390886 0.8191993
 0.78783105 0.76607502 0.8202787  0.77711256 0.75175047 0.79131176
 0.83651374 0.81995415 0.83620832 0.78213961 0.82245831 0.78184152
 0.81623254 0.80453244 0.76395543 0.81757019 0.78899999 0.80935575
 0.83806318 0.76677693 0.8301129  0.82492575 0.79233411 0.76313854
 0.77863636 0.83289865 0.82685642 0.82109516 0.77537401 0.81439328
 0.78257237 0.83016602 0.77699688 0.80271366 0.77371576 0.75591684
 0.80774614 0.78017788 0.76793415 0.77973989 0.82519988 0.79450468
 0.7587747  0.7751807  0.81362845 0.77273896 0.8274463  0.7716166
 0.80422856 0.81683876 0.83679015 0.83854314 0.80355935 0.79792856
 0.79546345 0.77255841 0.79998542 0.83668154 0

[7 7 7 ... 7 7 7]
[0.23658813 0.7343336  0.7873358  0.79949855 0.79854121 0.81186566
 0.78629734 0.81150634 0.83749889 0.77780485 0.81353455 0.80337271
 0.79062784 0.81898519 0.79777369 0.81836587 0.7874081  0.82903792
 0.82676275 0.81363494 0.76646276 0.79684687 0.83412374 0.80268477
 0.79086489 0.78650595 0.78257925 0.82008096 0.78390886 0.8191993
 0.78783105 0.76607502 0.8202787  0.77711256 0.75175047 0.79131176
 0.83651374 0.81995415 0.83620832 0.78213961 0.82245831 0.78184152
 0.81623254 0.80453244 0.76395543 0.81757019 0.78899999 0.80935575
 0.83806318 0.76677693 0.8301129  0.82492575 0.79233411 0.76313854
 0.77863636 0.83289865 0.82685642 0.82109516 0.77537401 0.81439328
 0.78257237 0.83016602 0.77699688 0.80271366 0.77371576 0.75591684
 0.80774614 0.78017788 0.76793415 0.77973989 0.82519988 0.79450468
 0.7587747  0.7751807  0.81362845 0.77273896 0.8274463  0.7716166
 0.80422856 0.81683876 0.83679015 0.83854314 0.80355935 0.79792856
 0.79546345 0.77255841 0.79998542 0.83668154 0